run: HW3_X1052165_Ser HW3_X1052165_Cli
HW3_X1052165_Ser: server.cpp
	g++ -std=c++11 -pthread server.cpp -o HW3_X1052165_Ser
HW3_X1052165_Cli: client.cpp
	g++ -std=c++11 -pthread client.cpp -o HW3_X1052165_Cli